# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 狐狸的AI技术笔记
subtitle: foxai.io
name: 狐狸Jimmy
email: sexyfoxtech@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  收集有用的AI技术，分享有趣的AI应用，记录AI学习历程。
baseurl: "" # the subpath of your site, e.g. /blog
url: https://foxai.io  # the base hostname and protocol for your site, e.g. http://example.com
repository: "foxai-io/foxai-io.github.io"
twitter_username: ArkarNZ
github_username:  xmany
logo: /assets/images/foxlogo88.png
twitter:
  username: "ArkarNZ"

domain: foxai.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com

# Theme settings
# theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes

minimal_mistakes_skin: dark

teaser: /assets/images/midjourney/midjourney-04-19-panda-1232x928.png

site.locale: zh

# Disable for now, because I can't fix the below issue
# breadcrumbs: true

# Will yield a breadcrumb like "Home / %e6%9c%ac%e7%ab%99%e4%bb%8b%e7%bb%8d / 本站介绍"
# permalink: /:categories/:title/

# Navigation settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      sidebar:
        nav: "sidebar"
  - scope:
      path: ""
      type: "posts"
    values:
      show_date: true
      comments: true
      sidebar:
        nav: "sidebar"
      # comments: true   # enable comments for all posts, later because discourse instance requires local docker server

# enable comments for all posts, later because discourse instance requires local docker server
# comments:
#   provider: "discourse"
#   discourse:
#     server: # meta.discourse.org

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/arkarnz"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/foxai-io/foxai-io.github.io"
    - label: "Discord"
      icon: "fab fa-discord"
      url: "https://discord.gg/Ryk5PuSTdp"


# Tags and categories
category_archive_path: "categories"
tag_archive_path: "tags"

plugins:
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

paginate: 10
paginate_path: "/page:num/"

# enable search
search: true

# google search console
google_site_verification: google-site-verification=fmdRhrauAjqvzE4U7mmQa0UJq4hamUS3eWZ-b8rgJnA

# enable comments
comments:
  provider: "disqus"
  disqus:
    shortname: "foxai"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
